version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing SAM CLI
      - pip install aws-sam-cli

  build:
    commands:
      - echo Starting SAM Build
      - sam validate # Validate the sam template
      - sam build --template template.yaml # build the sam template
      - sam deploy --template-file template.yaml --stack-name DarwillStack --no-execute-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM
  post_build:
    commands:
      - |
        # Constructing Build Logs URL
        BUILD_LOGS_URL="https://$AWS_REGION.console.aws.amazon.com/codesuite/codebuild/$(echo $CODEBUILD_BUILD_ARN | cut -f5 -d ':')/projects/$(echo $CODEBUILD_BUILD_ID | cut -f1 -d ':')/build/$CODEBUILD_BUILD_ID/logs?region=$AWS_REGION"

        # Update the pipeline name, stage name if the stage and action is other than manual-approval
        echo "Fetching Manual Approval Link..."
        APPROVAL_LINK="https://$AWS_REGION.console.aws.amazon.com/codesuite/codepipeline/pipelines/darwill-test-pipeline/view?region=$AWS_REGION#stage=manual-approval&action=manual-approval"

        # Update the teams URL
        echo "Sending message to Teams with build logs and approval link..."
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "text": "Build completed!\n\nPlease review the change set before proceeding further: [Build Logs]('"$BUILD_LOGS_URL"')\n\nYou can Approve or reject changes using this link: [Manual Approval]('"$APPROVAL_LINK"')."
            }' \
        "https://prod-22.centralindia.logic.azure.com:443/workflows/1eba6ea50afe4ec2aab09cbde3f9c45d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6VfNuGE9HT9n6XfsG-ya0OgxSwgpBzuEV2clNL7blTA"
artifacts:
  files:
    - "**/*"
  base-directory: .
