version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing SAM CLI
      - pip install aws-sam-cli
  build:
    commands:
      - echo Starting SAM Build
      - sam validate
      - sam build --template template.yaml
  # post_build:
  #   commands:
  #     - echo "Build completed, sending message to Teams..."
  #     - |
  #       curl -X POST -H "Content-Type: application/json" \
  #       -d '{"text": "SAM Build is completed, please review the changeset and move further"}' \
  #       "https://prod-22.centralindia.logic.azure.com:443/workflows/1eba6ea50afe4ec2aab09cbde3f9c45d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6VfNuGE9HT9n6XfsG-ya0OgxSwgpBzuEV2clNL7blTA" || echo "Failed to send message to Teams"
  # post_build:
  #   commands:
  #     - echo "Build completed, sending message to Teams..."
  #     - |
  #       curl -X POST -H "Content-Type: application/json" \
  #       -d '{"text": "SAM Build is completed. Please review the changeset and move further. \n\nYou can approve or reject the changes at the following link: [Approval Link](https://us-east-1.console.aws.amazon.com/codesuite/codepipeline/pipelines/darwill-pipeline/view?region=us-east-1#stage=Deploy&action=manual-approval)"}' \
  #       "https://prod-22.centralindia.logic.azure.com:443/workflows/1eba6ea50afe4ec2aab09cbde3f9c45d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6VfNuGE9HT9n6XfsG-ya0OgxSwgpBzuEV2clNL7blTA" || echo "Failed to send message to Teams"
  post_build:
    commands:
      - |
        echo "Constructing manual approval link..."
        APPROVAL_LINK="https://$AWS_REGION.console.aws.amazon.com/codesuite/codepipeline/pipelines/darwill-pipeline/view?region=$AWS_REGION#stage=Deploy&action=manual-approval"
        echo "Sending message to Teams with approval link: $APPROVAL_LINK"
        curl -X POST -H "Content-Type: application/json" \
        -d '{
              "text": "SAM Build is completed. Please review the changeset and move further.\n\nYou can approve or reject the changes at the following link: [Approval Link]('"$APPROVAL_LINK"')"
            }' \
        "https://prod-22.centralindia.logic.azure.com:443/workflows/1eba6ea50afe4ec2aab09cbde3f9c45d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6VfNuGE9HT9n6XfsG-ya0OgxSwgpBzuEV2clNL7blTA"

artifacts:
  files:
    - "**/*"
  base-directory: .
