version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10

  build:
    commands:
      - sam build
      - sam validate
      - sam deploy --no-execute-changeset --no-confirm-changeset --no-fail-on-empty-changeset

  post_build:
    commands:
      - sam deploy  --no-confirm-changeset --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --parameter-overrides Environment=staging