version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10

  build:
    commands:
      - sam build
      - sam validate
      - sam package --output-template-file template.yaml --no-confirm-changeset --no-fail-on-empty-changeset

artifacts:
  files:
    - template.yaml