version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo Installing SAM CLI
      - pip install aws-sam-cli
  build:
    commands:
      - echo Starting SAM Build
      - sam validate
      - sam build --template template.yaml
  post_build:
    commands:
      - echo "Build completed, sending message to Teams..."
      - |
        curl -X POST -H "Content-Type: application/json" \
        -d '{"text": "SAM Build is completed, please review the changeset and move further"}' \
        "https://prod-22.centralindia.logic.azure.com:443/workflows/1eba6ea50afe4ec2aab09cbde3f9c45d/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=6VfNuGE9HT9n6XfsG-ya0OgxSwgpBzuEV2clNL7blTA"
artifacts:
  files:
    - "**/*"
  base-directory: .
